name: CMake

on: [ pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt update
        sudo apt install gcc-10 g++-10 libgraphicsmagick-dev lcov
        sudo apt-get install build-essential checkinstall
        cd /opt
        sudo wget http://www.imagemagick.org/download/ImageMagick.tar.gz

        sudo tar xvzf ImageMagick.tar.gz
        cd $(ls | grep "ImageMagick-")
        sudo touch configure
        sudo ./configure
        sudo make
        sudo make install
        sudo ldconfig /usr/local/lib

    - name: Run unit tests
      uses: HorstBaerbel/action-ctest@1.0
      with:
        sourcedir: '.'
        builddir: 'build'
        cmakeoptions: '--CONFIG Debug -DMATH_COVERAGE=1 -DMATH_EXTENSIONS=numerics,ds'
        ctestoptions: '--coverage --extra-verbose'
